### ISSUE TITLE
Misleading comment in application.yml

### ISSUE THREAD

**Issue by JavierYuste** [rmartinsanta/mork#104]
In the default configuration within application.yml, the following comment is located in the "advanced" section: "# Collections.shuffle(RandomManager.getRandom()) should be used instead of Collections.shuffle() "

However, the mentioned method has the following signature and does not accept a RandomGenerator (which RandomManager.getRandom() provides): public static void shuffle(List<?> list, **Random** rnd)

Instead, the user should be guided to use CollectionUtil.shuffle(List<?> list), which is included in Mork.

**Comment by rmartinsanta** [comment]
Thx for reporting! Will be merged in v0.16.

advanced.block config properties have been removed from the template in recent versions, updated the config to reflect the changes. If an invalid random usage is detected, a link to https://mork-optimization.readthedocs.io/en/latest/quickstart/bestpractices/#customized-random-generator is provided to the user, which should explain what has happened and how to fix it.
