### ISSUE TITLE
Substitution of booleans to parameterise functionality. Enum

### ISSUE THREAD

**Issue by rubenmorante** [rmartinsanta/mork#124]
**Is your feature request related to a problem? Please describe.**
Substitution of booleans to parameterise functionality, as they should always have a descriptive comment about their use attached to them. 

**Describe the solution you'd like**
Use descriptively named enumerators, so that it abstracts from the type of the parameter and only reflects the functionality.

**Describe alternatives you've considered**
E.g:
ENABLE_FILTER / DISABLE_FILTER.

**Additional context**
----------

**Comment by rmartinsanta** [comment]
Done in 0f2219cd892e436aeda3fe7fd05cb217b837e3a1
