### ISSUE TITLE
Feature:  If dashboard is empty (App status: WAITING), provide to the user a "fetch data" button. 

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#22]
If the dashboard is empty, waiting for an event to start drawing charts and solutions (see image), the web should provide a button to simulate a ping to the server ([http://192.168.10.110:8081/ping](http://192.168.10.110:8081/ping)). Then, all passed events will be processed. 

![image](https://user-images.githubusercontent.com/26208138/132193726-f5af1e7f-b081-475e-b6f5-bee4946948b4.png)

**Comment by rmartinsanta** [comment]
Alternative: Once the websocket is connected and ready to start receiving data, ask the backend what is the latest stored event id to start synchronizing older event data.
