### ISSUE TITLE
Feature: Allow user to decide if app dies when finalizing experiments

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#23]
When an experiment ends, the application is killed. Therefore, the web-based dashboard for analyzing the results and solutions generated from the web is inaccessible. 

I consider it appropriate to allow the user to decide if he/she wants the process to die when the experiments finished. For this purpose, a new option should be added in the application.yml file

**Comment by rmartinsanta** [comment]
Nice feature, will be implemented for the v0.5 release.

**Comment by rmartinsanta** [comment]
Done in 1d3bb132fdd991602793c47665e62cae17aa10cf
