### ISSUE TITLE
Bug: The dashboard charts do not display a single point correctly. 

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#24]
As can be seen in the following image,  a single point cannot be visualized in the charts.

![image](https://user-images.githubusercontent.com/26208138/132492758-6d678a20-7acc-4882-91b7-e29b8880b838.png)

In order to display it, it is necessary to select the algorithm to hide it in the chart and then select it again to unhide it. 

This error does not seem to appear when there is more than one algorithm displayed on a graph.

**Comment by rmartinsanta** [comment]
@scaverod could not reproduce, could you provide an example?

**Comment by rmartinsanta** [comment]
Closed due to inactivity
