### ISSUE TITLE
Bug: Convergence chart is not consisten. 

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#26]
Just look:

![image](https://user-images.githubusercontent.com/26208138/132883373-76e8bcda-e16e-4cb5-acbd-be5a6f4aabed.png)

**Comment by rmartinsanta** [comment]
Bug in user program, added another validation to catch this type of mistakes (algorithm shortName duplication)
a04b475dd6649040bad5cc9ee01af098c6d4c879
