### ISSUE TITLE
Feature: Automatic update of metric when removing algorithm of Excel table results. 

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#32]
Since the deviation from the best solutions of an experiment is calculated when the data is passed to excel, it appears as a numerical value in the "Raw results" sheet. Therefore, when an algorithm that has better solutions is removed, the deviation from the best solutions is not updated. To obtain that value it is necessary to: rerun the experiment without that algorithm (easy wrong answer) or recalculate that value "by hand" (oh please, no!).  

How it could be solve it? The pivot tablet should automatically generate these metrics from the raw result sheet.

**Comment by rmartinsanta** [comment]
Implemented using a more complex formula, should work in Excel 2007+.
User can enable or disable calculation in Excel, by default only used when there is less than 2.000 rows.
@scaverod could you test it?

**Comment by scaverod** [comment]
Sure. I will let u know as soon as possible.

**Comment by rmartinsanta** [comment]
Feature works, closing
