### ISSUE TITLE
Question: What about hide/skip Main file from src folder

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#36]
As far as I know, the Main class in Mork should not be modifiable, so why show it in the source folder?

**Comment by rmartinsanta** [comment]
To give the user an obvious entry point, usually IDEs detect the main method and configure run buttons accordingly:
![image](https://user-images.githubusercontent.com/55482385/139837561-008c7dc1-b79f-4b7d-b1f3-8505c253de9b.png)
Although it is not necessary, removing it could cause more confusion, opinions?

**Comment by scaverod** [comment]
I was thinking about include the Main class in the core. 

Do IDE consider/detect Main classes of external libraries? If so, Main class will be totally invisible to the developer. 

If the developer needs to create its own Main class, he could do it based on the Main class of the core.

**Comment by rmartinsanta** [comment]
Not a priority right now, may review in the future. PRs always welcome though if there is interest.
