### ISSUE TITLE
Renaming classes and methods

### ISSUE THREAD

**Issue by rmartinsanta** [rmartinsanta/mork#46]
There are several naming inconsistencies across different classes and methods. Many things need to be renamed, what inconsistencies have you detected and what things would you rename?

**Comment by scaverod** [comment]
I've just made a PR renaming one of the variables of the Iterated Greedy class. Particularly, I've renamed  `private Shake<S, I> shake;` to ` private Shake<S, I> destructionReconstruction;`.  Why? The use  of "shake" comes from the VNS metaheuristic. It may lead to confusion.

**Comment by rmartinsanta** [comment]
Most work already done, some pending changes are subject to refactorings that will be merged before 0.10
