### ISSUE TITLE
What about define a Termination Criteria interface?

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#49]
Most of the algorithms combine some of the following criteria to determine when an algorithm should stop:

- Maximum number of iterations. 
- Maximum time. 
- Maximum number of iterations without improving. 

Also, it could be interesting to set a minimum number of iterations the algorithm should be executed before stop. 

When developing this interface, it should be taken into consideration that users could want to define their own termination criteria.

**Comment by rmartinsanta** [comment]
As of now, each algorithm has its own termination criteria, and I would keep it this way for simplicity. If many algorithms have common termination criteria we can revisit this issue.

Users can already define their own termination criteria for their custom algorithms as they wish. By forcing a common interface we may be forcing users to implement termination criterias in their algorithms they may not be interested in.
