### ISSUE TITLE
Check getShortName and toString of algorithms

### ISSUE THREAD

**Issue by scaverod** [rmartinsanta/mork#50]
I have found several potential bugs in various algorithms with methods related to algorithm name generation. That is: `getShortName()` and `toString()`. 

The name of the algorithms must be consistent: on the one hand, the name structure must be consistent between the different algorithms, and, on the other hand, the name must be exported correctly to excel (or csv). 

In this last case (exporting to xlxs)  it is important to check the size of the algorithm name, sometimes is truncated.

**Comment by rmartinsanta** [comment]
Going to implement a hard limit on maximum algorithm shortname length. The validation will run before the experiment starts, if any algorithm shortname length is greater than the limit it.
