### ISSUE TITLE
TSP Example

### ISSUE THREAD

**Issue by isaaclo97** [rmartinsanta/mork#69]
https://mork-optimization.readthedocs.io/en/latest/examples/TSP/

- Images does not work.
- In section 7 -> "Testing in Mork There are many ways, testing is one way  (go to **section XXX** for an example of Test implementation in Mork)" Section XXX?

**Comment by scaverod** [comment]
According to the second point of the issue: Section XXX has not been changed because de documentation about testing in mork is not finished yet, isn't it @rmartinsanta ?
