### ISSUE TITLE
Add custom solution params to results

### ISSUE THREAD

**Issue by rmartinsanta** [rmartinsanta/mork#99]
Allow the user to define custom solution properties that will be automatically serialized to result files.
The user would define something like:
```java
Map<String, Method> properties = Map.of("miCustomProperty", Solution::calculateMyCustomProperty);
```
After the algorithm is executed, the value for "miCustomProperty" would be calculated using the provided function and passed to the results object where it will be available in the serializers.

**Comment by scaverod** [comment]
Review in process

**Comment by rmartinsanta** [comment]
Done in #100
